version: "3"
services:
  api:
    container_name: api
    image: $docker_user_name/$api_image_name:$api_image_tag
    restart: always
    ports:
      - "80:80"
    network_mode: "host"
    depends_on:
      - database

  database:
    container_name: database 
    image: $docker_user_name/$mssql_image_name:$mssql_image_tag
    restart: always
    ports:
      - "1433:1433"
    network_mode: "host"

