version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-ozgur
    image: ozgurtaylankarakoc/api-vero:1.0
    restart: always
    ports:
      - "80:80"
    network_mode: "host"
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile-mssql
    container_name: database 
    image: ozgurtaylankarakoc/db-vero:1.0
    restart: always
    ports:
      - "1433:1433"
    network_mode: "host"

