FROM mcr.microsoft.com/mssql/server:2022-latest
USER root
ENV ACCEPT_EULA Y
ENV MSSQL_SA_PASSWORD Un!q@to2023
COPY db.sql /usr/src/db.sql
EXPOSE 1433
RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 30 \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -i /usr/src/db.sql
CMD ["/opt/mssql/bin/sqlservr"]